#!/usr/bin/env bash
# Transfers a file from our client to a server
# Path to file="$1"
# ip="$2"
# Username="$3"
# Path to ssh key="$4"
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
