#!/usr/bin/env bash
# Install nginx
# Configure it to listening on port 80
# Print "Hellow World"

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# configure nginx to listen on port 80
ufw allow 'Nginx HTTP'

# Creating Sample Page
echo "Hello World!" > /var/www/html/index.html

# Start Nginx
service nginx start
