#!/usr/bin/env bash
# Configure a new Nginx server so that 
# /redirect_me is redirecting to another page

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Creating Sample Page
echo "Hello World!" > /var/www/html/index.html

# add the following configuration to the existing server block
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/@themathsclub permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx start
