#!/usr/bin/env bash
# Installs and configures HAproxy using roundrobin algorithm

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configures HAProxy using roundrobin algorithm
echo "
frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server 402402-web-01 54.90.40.60:80 check
        server 402402-web-02 54.159.1.227:80 check
">> /etc/haproxy/haproxy.cfg

# Enables HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
